import Head from 'next/head'
import { useAppSelector, useAppDispatch } from '../store'
import { decrement, increment } from '../features/home/slices/counter'
import SignInForm from '../core/components/SignInForm'

export default function Home() {
  const count = useAppSelector((state) => state.counter.value)
  const { user } = useAppSelector((state) => state.auth)
  const dispatch = useAppDispatch()

  return (
    <div className="flex h-screen items-center justify-center bg-purple-100">
      {!user ? <SignInForm /> : null}
      <Head>
        <title>KDN stack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="flex space-x-10">
          <button className="rounded-md border-none bg-slate-200 px-3 text-6xl text-purple-500" onClick={() => dispatch(decrement())}>
            -
          </button>
          <h1 className="text-6xl font-bold text-orange-500">{count}</h1>
          <button className="rounded-md border-none bg-slate-200 px-3 text-6xl text-purple-500" onClick={() => dispatch(increment())}>
            +
          </button>
        </div>
      </main>
    </div>
  )
}
